name: attendance_payroll_app
description: "Company Attendance & Payroll with Google Sheets"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2

  # Firebase core (for Google Sign-In)
  firebase_core: ^2.22.0
  google_sign_in: ^6.2.1

  # Optional: state management
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Optional assets
  # assets:
  #   - assets/google_logo.png
